name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # unit tests
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: mattallty/jest-github-action@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
        working-directory: "caltest"